---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gateway-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.gateway: glob:*
spec:
  releaseName: gateway-dev
  forceUpgrade: true
  chart:
    git: git@github.com:wynnel/puma-gitops
    path: charts/gateway
    ref: master
  valuesFrom:
  - secretKeyRef:
      name: image-creds
      key: image-creds.yaml
  - secretKeyRef:
      name: gateway-license
      key: license.yaml
  - configMapKeyRef:
      name: env-values
      key: env.yaml
  values:
    replicaCount: 1
    container:
      image: docker.sandbox2.apimgcp.com/repository/docker-hosted/gateway
      tag: '26'
    imageCredentials:
      name: "docker.sandbox2.apimgcp.com"
      registry: "docker.sandbox2.apimgcp.com"
      username: "admin"
    hazelcast:
      enabled: false
    influxdb:
      host: "apim-service-metrics-runtime-influxdb.default"
    service:
      ports:
      - name: http
        internal: 8080
        external: 80
      - name: https
        internal: 8443
        external: 443
    gateway:
      ENV.CONTEXT_VARIABLE_PROPERTY.influxdb.influxdb: "apim-service-metrics-runtime-influxdb.default"
      ENV.CONTEXT_VARIABLE_PROPERTY.influxdb.tags: "env=dev"





